# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-08-20 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_req',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
