# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-08-19 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=255)),
                ('Description', models.TextField(verbose_name='Describ')),
                ('Content', models.ImageField(blank=True, upload_to='Content/')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo_1', models.ImageField(blank=True, upload_to='OurTeam/')),
                ('Name1', models.CharField(max_length=150)),
                ('Designation1', models.CharField(max_length=200)),
                ('Details1', models.CharField(max_length=600)),
                ('Photo_2', models.ImageField(blank=True, upload_to='OurTeam/')),
                ('Name2', models.CharField(max_length=150)),
                ('Designation2', models.CharField(max_length=200)),
                ('Details2', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressBer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.IntegerField()),
                ('First_description', models.CharField(max_length=30)),
                ('Second', models.IntegerField()),
                ('Second_description', models.CharField(max_length=30)),
                ('Third', models.IntegerField()),
                ('Third_description', models.CharField(max_length=30)),
                ('Fourth', models.IntegerField()),
                ('Fourth_description', models.CharField(max_length=30)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(blank=True, upload_to='sliderImage/')),
                ('photo_1_header', models.CharField(max_length=100)),
                ('photo_1_details', models.CharField(max_length=100)),
                ('photo_2', models.ImageField(blank=True, upload_to='sliderImage/')),
                ('photo_2_header', models.CharField(max_length=100)),
                ('photo_2_details', models.CharField(max_length=100)),
                ('photo_3', models.ImageField(blank=True, upload_to='sliderImage/')),
                ('photo_3_header', models.CharField(max_length=100)),
                ('photo_3_details', models.CharField(max_length=100)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.TextField(blank=True)),
                ('Name', models.CharField(max_length=40)),
                ('Designation', models.CharField(max_length=30)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
