# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-08-19 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='Content',
            new_name='content_image',
        ),
    ]
